use_frameworks!

platform :ios, '9.0'

target 'AZImageSlider_Example' do
  pod 'AZImageSlider', :path => '../'

  target 'AZImageSlider_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
